### PR TITLE
Add tests for selection plugin

### PR DESCRIPTION
**Pull request by octavianCraciun**
Related to this PR: https://github.com/ni-kismet/webcharts-legends/pull/20

### CODE REVIEW

**Comment by octavianCraciun** [comment]
Looks like i need to add more tests.

**Comment by cristiingineru** [comment]
expect(25.000000000000004).toBeCloseTo(25, 2);

**Comment by cristiingineru** [comment]
Regarding the test coverage/count my concern is related to this function not beeing called while testing not even once:
```
plot.hooks.drawOverlay.push(function (plot, ctx) { ... }
```

See https://coveralls.io/builds/11368417/source?filename=jquery.flot.selection.js#L439

The drawOverlay hook is called by a timer, so you should either have a test that mocks the time or forces the overlay drawing in the same time with draw(). See:
https://github.com/octavianCraciun/engineering-flot/blob/2d60c3e392685c084b9ab3311f322e1eeddabf0d/jquery.flot.js#L152 and https://github.com/octavianCraciun/engineering-flot/blob/2d60c3e392685c084b9ab3311f322e1eeddabf0d/jquery.flot.js#L2649

**Comment by cristiingineru** [comment]
This is too old. Please update and open a new PR.

**Pull request closed without merging**
