### PR TITLE
add decimation points for bars and poins. For now the bars will use the same same decimation entry as the line charts.

### PR DESCRIPTION
**Pull request by cipix2000**
I've did also a lot of cleanup in this PR:
* moved flot legends to a plugin
* removed code for drawing shadows
* enabled eslint for tests

This should result in an increase in test coverage by removing unused code

### CODE REVIEW

**Comment by cristiingineru** [comment]
The new file was not added to karma.config.js. Was this on purpose? What is the strategy for the files with 0 coverage?

**Comment by cristiingineru** [comment]
There are more examples that are using the legend. I think all of them should be updated to include the new plugin file.

**Comment by cipix2000** [comment]
we don't have tests for the legend and we don't use it in webcharts. The strategy for now is to now add untested/unused by webcharts files to the coverage. Long term we should test all the plugins in the repo or remove the untested ones

**Comment by cipix2000** [comment]
the plan for the engineering-examples examples is to fix all of them (hopefully this Friday)

**Pull request merged**
