### PR TITLE
fix interpolation when outside the data range provided

### PR DESCRIPTION
**Pull request by J-France**
Do not interpolate outside the range of data provided.

Looks like this repo also has CI issues for chrome

### CODE REVIEW

**Comment by jattasNI** [comment]
@atmgrifter00 has a fix for the CI in [PR 220](https://github.com/ni-kismet/engineering-flot/pull/220)

**Comment by atmgrifter00** [comment]
Following up on Jesse's comment, my pull request is for an orphan release branch, and the changes to fix the CI won't make it into master. I recommend you copy what I did from this pull request:

https://github.com/ni-kismet/engineering-flot/pull/220

and update yours with the same change to the travis.yml file.

**Comment by J-France** [comment]
@ralucaportase Should the dist update be done as part of this commit or when bumping the version of the package?

**Comment by ralucaportase** [comment]
We used to update the dist file in each commit to be sure that all is up to date and we don't miss it on release :)

**Pull request merged**
